plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - architecture_root.md
  - federation.md
  - mining.md
  - packopener.md
  - shining.md
  - token.md
  - vesting.md
  - PULL_REQUEST_TEMPLATE.md